# 1️⃣ Mean for Ungrouped Data

In [1]:
data = [10, 20, 30, 40, 50]

In [2]:
mean_value = sum(data) / len(data)
print(mean_value)

30.0

#  Using NumPy

In [3]:
import numpy as np

mean_value = np.mean(data)
print(mean_value)

30.0

# Using Pandas

In [4]:
import pandas as pd

s = pd.Series(data)
print(s.mean())

30.0

# Mean for Grouped Data

# Grouped data means values with frequencies.

In [5]:
data = {
    'class': ['A', 'A', 'B', 'B', 'B'],
    'score': [70, 80, 60, 75, 85]
}

df = pd.DataFrame(data)

In [6]:
group_mean = df.groupby('class')['score'].mean()
print(group_mean)

class
A    75.000000
B    73.333333
Name: score, dtype: float64

In [7]:
import numpy as np

values = [10, 20, 30]
weights = [2, 3, 5]

weighted_mean = np.average(values, weights=weights)
print(weighted_mean)
#         avg = sum(a * weights) / sum(weights)

23.0

# Geometric Mean (GM)

In [8]:
from scipy.stats import gmean

data = [2, 4, 8, 16]

gm = gmean(data)
print(gm)

5.656854249492379

# Harmonic Mean (HM)

In [9]:
from scipy.stats import hmean

data = [10, 20, 40]

hm = hmean(data)
print(hm)

17.14285714285714

#  Median (Ungrouped)

In [10]:
import numpy as np

median_value = np.median(data)
print(median_value)

20.0

# Mode (Ungrouped)

In [177]:
import pandas as pd
data = [10, 20, 40, 40, 20]
mode_value = pd.Series(data).mode()
#print(mode_value.tolist())
mode_value

0    20
1    40
dtype: int64

# Grouped Data

In [16]:
import numpy as np

values = [10, 20, 30]
freq = [2, 3, 5]

expanded = np.repeat(values, freq)
median_grouped = np.median(expanded)
print(median_grouped)

25.0

In [18]:
import pandas as pd

df = pd.DataFrame({'x': values, 'f': freq})
df

    x  f
0  10  2
1  20  3
2  30  5

In [19]:

mode_grouped = df.loc[df['f'].idxmax(), 'x']
print(mode_grouped)

30

# Range

In [20]:
data = [10, 20, 30, 40, 50]

In [21]:
data_range = max(data) - min(data)
print(data_range)

40

In [23]:
import numpy as np

# Population variance
var_population = np.var(data)

# Sample variance
var_sample = np.var(data)

print(var_population, var_sample)

200.0 200.0

In [163]:
import pandas as pd

s = pd.Series(data)

# Sample variance (default)
print(s.var())

1530.6964285714287

In [154]:
# Population STD
std_population = np.std(data)

# Sample STD
std_sample = np.std(data, ddof=1)

print(std_population, std_sample)

104.56895651514682 128.07029319869616

In [26]:
print(s.std())

15.811388300841896

# How to Calculate Skewness and Kurtosis python

In [27]:
data = [10, 12, 15, 18, 20, 100]

In [34]:
import pandas as pd
data = [10, 12, 15, 18, 20, 100]

s = pd.Series(data)

skewness = s.skew()
kurtosis = s.kurt()   #  (excess kurtosis)

print(skewness, kurtosis)

2.388168714824472 5.7672301535346175

In [162]:
import pandas as pd
data = [10, 12, 15, 18, 20, 100, 100, 20]

s = pd.Series(data)
s.mode()[0]

np.int64(20)

In [190]:
df = pd.read_csv('Cleaned_Final_DataSet.csv')
df.head(2)
X = df.iloc[:, 2].values
X = pd.Series(X)
X.skew()
X.kurt()
X.mode()
X.median()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,coffee,-0.741832,-0.765858,0.130435,credit card,takeaway,2023-09-08
1,TXN_4977031,cake,0.702686,0.038066,0.478261,cash,in-store,2023-05-16

In [195]:
X = df.iloc[:, 2].values
X = pd.Series(X)
X.skew()

np.float64(-0.005339359450362572)

In [196]:
X.kurt()

np.float64(-1.2277093633156915)